version: '3.9'
services:
  next-redux:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    ports:
      - '3000:3000'
